### ISSUE TITLE
dc.get_resource fails with connection issue (specific to HPA)

### ISSUE THREAD

**Issue by josenimo** [saezlab/decoupler-py#160]
First, thank you for this amazing package, this is my go to for biological inference of my systems biology analysis, I recommended every time I get. 

**Describe the bug**
I try to get HPA_tissue resource, and it loops trying to connect.

**To Reproduce**
```python
import decoupler as dc
HPA_tissue = dc.get_resource("HPA_tissue")
```

**Expected behavior**
I expect the database to be loaded like msigdb, or Progeny

**System**
 - OS: macOS Sonoma 14.0.0
 - Python version 3.12.7
 - Versions of libraries involved see mamba list at the bottom

**Additional context**
<details>
<summary> Traceback </summary>

```python
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=5, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /annotations?entity_types=protein&format=tsv&resources=HPA_tissue
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=5, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /annotations?entity_types=protein&format=tsv&resources=HPA_tissue
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=5, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /annotations?entity_types=protein&format=tsv&resources=HPA_tissue
WARNING:root:Failed to download from `https://omnipathdb.org/`.
WARNING:root:urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/decoupler/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/decoupler/lib/python3.12/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/decoupler/lib/python3.12/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/decoupler/lib/python3.12/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/decoupler/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/decoupler/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='omnipathdb.org', port=443): Max retries exceeded with url: /annotations?entity_types=protein&format=tsv&resources=HPA_tissue (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/decoupler/lib/python3.12/site-packages/omnipath/_core/downloader/_downloader.py", line 143, in maybe_download
    res = self._download(req)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/decoupler/lib/python3.12/site-packages/omnipath/_core/downloader/_downloader.py", line 178, in _download
    with self._session.send(
         ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/decoupler/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/decoupler/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='omnipathdb.org', port=443): Max retries exceeded with url: /annotations?entity_types=protein&format=tsv&resources=HPA_tissue (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))

WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=5, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /annotations?entity_types=protein&format=tsv&resources=HPA_tissue

```

</details>

<details>
<summary> mamba list </summary>

```
# packages in environment at /opt/homebrew/Caskroom/mambaforge/base/envs/decoupler:
#
# Name                    Version                   Build  Channel
adjusttext                1.3.0              pyhd8ed1ab_0    conda-forge
anndata                   0.10.9             pyhd8ed1ab_0    conda-forge
anyio                     4.6.2.post1        pyhd8ed1ab_0    conda-forge
appnope                   0.1.4              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py312h024a12e_5    conda-forge
arpack                    3.9.1           nompi_h593882a_101    conda-forge
array-api-compat          1.9.1              pyhd8ed1ab_0    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attrs                     24.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.8.0                h6935006_7    conda-forge
aws-c-cal                 0.8.0                h8a8b6a7_1    conda-forge
aws-c-common              0.10.0               h7ab814d_0    conda-forge
aws-c-compression         0.3.0                h8a8b6a7_1    conda-forge
aws-c-event-stream        0.5.0                h53a7d5e_4    conda-forge
aws-c-http                0.9.0                h007639a_5    conda-forge
aws-c-io                  0.15.1               hb495e35_1    conda-forge
aws-c-mqtt                0.11.0               h6850007_5    conda-forge
aws-c-s3                  0.7.0                h2bee52d_7    conda-forge
aws-c-sdkutils            0.2.1                h0b63f77_0    conda-forge
aws-checksums             0.2.0                h8a8b6a7_1    conda-forge
aws-crt-cpp               0.29.3               h7abc90e_2    conda-forge
aws-sdk-cpp               1.11.407             h124cfea_9    conda-forge
azure-core-cpp            1.14.0               hd50102c_0    conda-forge
azure-identity-cpp        1.10.0               hc602bab_0    conda-forge
azure-storage-blobs-cpp   12.13.0              h7585a09_1    conda-forge
azure-storage-common-cpp  12.8.0               h9ca1f76_1    conda-forge
azure-storage-files-datalake-cpp 12.12.0              hcdd55da_1    conda-forge
babel                     2.16.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
bleach                    6.2.0              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hd74edd7_2    conda-forge
brotli-bin                1.1.0                hd74edd7_2    conda-forge
brotli-python             1.1.0           py312hde4cb15_2    conda-forge
bzip2                     1.0.8                h99b78c6_7    conda-forge
c-ares                    1.34.2               h7ab814d_0    conda-forge
ca-certificates           2024.8.30            hf0a4a13_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py312h0fad829_0    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.3.0           py312h4721b07_2    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
debugpy                   1.8.7           py312hde4cb15_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
decoupler-py              1.8.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
docrep                    0.3.2              pyh44b312d_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.1.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.54.1          py312ha0ccf2a_1    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hadb7bae_2    conda-forge
get-annotations           0.1.2              pyhd8ed1ab_0    conda-forge
gflags                    2.2.2             hf9b8971_1005    conda-forge
glog                      0.7.1                heb240a5_0    conda-forge
glpk                      5.0                  h6d7a090_0    conda-forge
gmp                       6.3.0                h7bae524_2    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5py                      3.12.1          nompi_py312h3cd0824_102    conda-forge
hdf5                      1.14.3          nompi_hec07895_105    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.6              pyhd8ed1ab_0    conda-forge
httpx                     0.27.2             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       75.1                 hfee45f7_0    conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
igraph                    0.10.13              h762ac30_0    conda-forge
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
importlib_metadata        8.5.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.5              pyhd8ed1ab_0    conda-forge
inflect                   7.4.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.29.5             pyh57ce528_0    conda-forge
ipython                   8.29.0             pyh707e725_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
json5                     0.9.25             pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py312h81bd7bf_1    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2024.10.1          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.23.0               hd8ed1ab_0    conda-forge
jupyter-lsp               2.2.5              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2              pyh31011fe_1    conda-forge
jupyter_events            0.10.0             pyhd8ed1ab_0    conda-forge
jupyter_server            2.14.2             pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_0    conda-forge
jupyterlab                4.2.5              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_1    conda-forge
jupyterlab_server         2.27.3             pyhd8ed1ab_0    conda-forge
kaleido                   0.2.1                    pypi_0    pypi
kiwisolver                1.4.7           py312h6142ec9_0    conda-forge
krb5                      1.21.3               h237132a_0    conda-forge
lcms2                     2.16                 ha0e7c42_0    conda-forge
legacy-api-wrap           1.4                pyhd8ed1ab_1    conda-forge
leidenalg                 0.10.2          py312h20a0b95_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libabseil                 20240722.0      cxx17_hf9b8971_1    conda-forge
libaec                    1.1.3                hebf3989_0    conda-forge
libarrow                  18.0.0           h445c139_4_cpu    conda-forge
libarrow-acero            18.0.0           h286801f_4_cpu    conda-forge
libarrow-dataset          18.0.0           h286801f_4_cpu    conda-forge
libarrow-substrait        18.0.0           h6a6e5c5_4_cpu    conda-forge
libblas                   3.9.0           25_osxarm64_openblas    conda-forge
libbrotlicommon           1.1.0                hd74edd7_2    conda-forge
libbrotlidec              1.1.0                hd74edd7_2    conda-forge
libbrotlienc              1.1.0                hd74edd7_2    conda-forge
libcblas                  3.9.0           25_osxarm64_openblas    conda-forge
libcrc32c                 1.1.2                hbdafb3b_0    conda-forge
libcurl                   8.10.1               h13a7ad3_0    conda-forge
libcxx                    19.1.3               ha82da77_0    conda-forge
libdeflate                1.22                 hd74edd7_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h93a5062_2    conda-forge
libevent                  2.1.12               h2757513_1    conda-forge
libexpat                  2.6.4                h286801f_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_3    conda-forge
libgfortran5              13.2.0               hf226fd6_3    conda-forge
libgoogle-cloud           2.31.0               h8d8be31_0    conda-forge
libgoogle-cloud-storage   2.31.0               h7081f7f_0    conda-forge
libgrpc                   1.67.1               hc70892a_0    conda-forge
libhwloc                  2.11.2          default_h3f80f97_1000    conda-forge
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libjpeg-turbo             3.0.0                hb547adb_1    conda-forge
liblapack                 3.9.0           25_osxarm64_openblas    conda-forge
libleidenalg              0.11.1               h1995070_0    conda-forge
libllvm14                 14.0.6               hd1a9a77_4    conda-forge
libnghttp2                1.64.0               h6d7220d_0    conda-forge
libopenblas               0.3.28          openmp_hf332438_1    conda-forge
libparquet                18.0.0           hda0ea68_4_cpu    conda-forge
libpng                    1.6.44               hc14010f_0    conda-forge
libprotobuf               5.28.2               h8f0b736_0    conda-forge
libre2-11                 2024.07.02           h2348fd5_1    conda-forge
libsodium                 1.0.20               h99b78c6_0    conda-forge
libsqlite                 3.47.0               hbaaea75_1    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libthrift                 0.21.0               h64651cc_0    conda-forge
libtiff                   4.7.0                hfce79cd_1    conda-forge
libutf8proc               2.8.0                h1a8c8d9_0    conda-forge
libwebp-base              1.4.0                h93a5062_0    conda-forge
libxcb                    1.17.0               hdb1d25a_0    conda-forge
libxml2                   2.13.4               h8424949_2    conda-forge
libzlib                   1.3.1                h8359307_2    conda-forge
littleutils               0.2.4              pyhd8ed1ab_0    conda-forge
llvm-openmp               19.1.3               hb52a8e5_0    conda-forge
llvmlite                  0.43.0          py312ha9ca408_1    conda-forge
loguru                    0.7.2           py312h81bd7bf_2    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
markupsafe                3.0.2           py312ha0ccf2a_0    conda-forge
matplotlib-base           3.9.2           py312h9bd0bc6_1    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
more-itertools            10.5.0             pyhd8ed1ab_0    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
natsort                   8.4.0              pyhd8ed1ab_0    conda-forge
nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
nbconvert-core            7.16.4             pyhd8ed1ab_1    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  h7bae524_1    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
networkx                  3.4.2              pyhd8ed1ab_1    conda-forge
notebook                  7.2.2              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_0    conda-forge
numba                     0.60.0          py312h41cea2d_0    conda-forge
numpy                     1.26.4          py312h8442bc7_0    conda-forge
omnipath                  1.0.8              pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.2                h9f1df11_0    conda-forge
openssl                   3.4.0                h39f12f2_0    conda-forge
orc                       2.0.2                hcb3c8b3_2    conda-forge
outdated                  0.2.2              pyhd8ed1ab_1    conda-forge
overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.3           py312hcd31e36_1    conda-forge
pandas-flavor             0.6.0              pyhd8ed1ab_2    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    11.0.0          py312haf37ca6_0    conda-forge
pingouin                  0.5.5              pyhd8ed1ab_0    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.3.6              pyhd8ed1ab_0    conda-forge
plotly                    5.24.1             pyhd8ed1ab_0    conda-forge
prometheus_client         0.21.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.48             pyha770c72_0    conda-forge
psutil                    6.1.0           py312h0bf5046_0    conda-forge
pthread-stubs             0.4               hd74edd7_1002    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
pyarrow                   18.0.0          py312h1f38498_1    conda-forge
pyarrow-core              18.0.0          py312hc40f475_1_cpu    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pynndescent               0.5.13             pyhff2d567_0    conda-forge
pyobjc-core               10.3.1          py312hd24fc31_1    conda-forge
pyobjc-framework-cocoa    10.3.1          py312hd24fc31_1    conda-forge
pyparsing                 3.2.0              pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.12.7          h739c21a_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-igraph             0.11.6          py312h3144bb4_2    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    5_cp312    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.2           py312h024a12e_1    conda-forge
pyzmq                     26.2.0          py312hf8a1cbd_3    conda-forge
qhull                     2020.2               h420ef59_5    conda-forge
re2                       2024.07.02           hcd0e937_1    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpds-py                   0.21.0          py312hcd83bfe_0    conda-forge
scanpy                    1.10.3             pyhd8ed1ab_0    conda-forge
scikit-learn              1.5.2           py312h387f99c_1    conda-forge
scipy                     1.14.1          py312h20deb59_1    conda-forge
seaborn                   0.13.2               hd8ed1ab_2    conda-forge
seaborn-base              0.13.2             pyhd8ed1ab_2    conda-forge
send2trash                1.8.3              pyh31c8845_0    conda-forge
session-info              1.0.0              pyhd8ed1ab_0    conda-forge
setuptools                75.3.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.1                hd02b534_0    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.4          py312h755e627_0    conda-forge
stdlib-list               0.11.0             pyhd8ed1ab_0    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tbb                       2022.0.0             h0cbf7ec_0    conda-forge
tenacity                  9.0.0              pyhd8ed1ab_0    conda-forge
terminado                 0.18.1             pyh31c8845_0    conda-forge
texttable                 1.7.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tinycss2                  1.4.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tomli                     2.0.2              pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py312h024a12e_1    conda-forge
tqdm                      4.67.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
typeguard                 4.4.1              pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.9.0.20241003     pyhff2d567_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
umap-learn                0.5.7           py312h81bd7bf_0    conda-forge
unicodedata2              15.1.0          py312h0bf5046_1    conda-forge
upsetplot                 0.9.0              pyhd8ed1ab_0    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webcolors                 24.8.0             pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.16.0          py312h024a12e_1    conda-forge
xarray                    2024.10.0          pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hd74edd7_1    conda-forge
xorg-libxdmcp             1.1.5                hd74edd7_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zeromq                    4.3.5                h9f5b81c_6    conda-forge
zipp                      3.20.2             pyhd8ed1ab_0    conda-forge
zstandard                 0.23.0          py312h15fbf35_1    conda-forge
zstd                      1.5.6                hb46c0d2_0    conda-forge
```
</details>

**Comment by josenimo** [comment]
so testing things out, it seems that it is a specific problem with HPA_tissue.
HPA_secretome, HPA_subcellular work

**Comment by deeenes** [comment]
Hello @josenimo, The cache partition of the server run out of space, now it should be working again.

Thanks for reporting, and apologies for the inconvenience!
